#!/bin/bash

PATH_TO_DIR=/root/opi_config

source $PATH_TO_DIR/params.conf


# Wait for interface availability
function wait_for_interface {
	DIRECTORY=/sys/class/net/$1
	while true; do
		if [[ -d $DIRECTORY ]]; then
			echo Interface detected
			break		
		fi
		sleep 1
	done
}

if [[ $1 == $WLAN ]] || [[ $1 == $ADHOC ]]; then 
	if [[ $1 == $WLAN ]]; then 
		# Wait until wlan0 interface is available
		wait_for_interface $WLAN
		# Configure wlan in adhoc mode
		/sbin/iwconfig $WLAN mode ad-hoc channel 1 essid test_adhoc ap F2:35:8E:87:3B:97
		/sbin/ifconfig $WLAN $W_IP netmask $W_MASK
	fi

	if [[ $1 == $ADHOC ]]; then
        	# Wait until adhoc0 interface is available	
		wait_for_interface $ADHOC
		# Assing required ip and netmask for virtual adhoc0 interface
		/sbin/ip addr add $A_IP/$A_MASK dev $ADHOC
		# Remove autogenerated ipv6
		/sbin/ip -6 addr flush dev $ADHOC

		if [[ $GATEWAY == false ]]; then
			# Set route for sl monitoring and ntp
			ip route add 136.243.213.206/32 dev $ADHOC
			ip route add 8.8.8.8 dev $ADHOC
		fi
	fi
else
	echo No such interface 
	exit 1
fi

